apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: flask-container
        image: mim9/todo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "mysql://root:password@mysql/todolist_db"
        - name: SECRET_KEY
          value: "your_secret_key"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: LoadBalancer
  selector:
    app: todo-app
  ports:
  - port: 80
    targetPort: 5000
