apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-todo
  template:
    metadata:
      labels:
        app: flask-todo
    spec:
      containers:
      - name: flask-todo
        image: mim9/flask-todo-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: mysql://root@mysql-service:3306/todolist_db
        - name: SECRET_KEY
          value: your-secret-key
